notifications:
  email: false
language: node_js
node_js:
- '0.10'
- '0.12'
before_script:
- npm install -g gulp
before_install:
- npm i
install:
- npm test
deploy:
  provider: npm
  email: me@drjova.com
  api_key:
    secure: nI0DXNLnDidttVW0Gyou4wqVjLyHOjGDf1RJ8+5DV2ssm2WEihmlO20HZYakSuSlkh6ZnCKjiXZvBkTJT5u0Uv+1XSlRb28fjPugPL/Sh/YwQUbHxIyrxBIfT/EkDtGUuRCM8pvFZcMUfhGDoZDXGsJdjnXJt4WLRT+bpJnn0DUku7dJQrzX5EdwP1ROZBTxsmdAvf+MPN2i1aWOqOoii57DxL0WM5qZcG/sdgO9OON6IxV+334CXCIjUQ77RIZ5xRcBpohMH/8cT1tuYtsw494yx4pVuTeTQE9N0W8GbHgHmPwBbYvIiFsMm5VI6pjdvpU3yHDjxXvvtwfjrbuYZF8eAHbK6ofXzYlmICl69PmL9hLtQzJYwGjctVgjkHkYDJ4Sdy9AdYAs30GwoPAMGuGLuSfKG1t3YHwRZSCCP9L79H2mdi+92PC2KlojT7wEJXnwpKXZtewXovCiE5R8KY0aD9/GqUlUaaqVsWfU4LbGpsjUSU9h3DNc0UzkxM+QAi/BoGgXgIE29HUwEv7lBnN6IBIQbEDRL1K/TolqysPe+XOAqTzTnRTomdbJDcaLf83K2e58duUA+cnrIQnykMh9qOy2EWARbpC9LOJtTSAPF85n0hG+6RoyGFlJHCk0ksoWSq5pqSSmrGpFhDMzg7w3ln1LhyWpvReWUyviQBI=
  on:
    tags: true
    repo: drjova/invenio-search-js
    branch: structure
